### ISSUE TITLE
Virtual Keyboard fills the whole screen

### ISSUE THREAD

**Issue by luizlinux** [m-wynn/sddm_wynn-theme#11]
When using this theme on OpenSuse Tumbleweed a virtual keyboard fills the whole screen.
Is this a feature? Can this be disabled?

The workaround I've figured is to press enter then login fails and the keyboard disappears.

**Comment by EricKotato** [comment]
If you want to disable virtual keyboard in SDDM, you can try to edit `/etc/sddm.conf` and change
```
InputMethod=qtvirtualkeyboard
```
to
```
InputMethod=
```

Or you need support for virtual keyboard?

**Comment by luizlinux** [comment]
Thanks, it worked.
I wonder why isn't this the default behavior..

**Comment by EricKotato** [comment]
Well, virtual keyboard support is a long-standing [SDDM issue](https://github.com/sddm/sddm/issues/100), which, I guess, is only partially resolved. Reason for `qtvirtualkeyboard` as default `InputMethod` in description of [this commit](https://github.com/sddm/sddm/commit/ef7e0812dab3d2e56b2ad388e6c45ca5c84391d7).

**Comment by m-wynn** [comment]
Closing this, as any keyboard issues appear to be with sddm.  This theme acts exactly the same as the default Fedora theme.

There is a button in the bottom right of the keyboard to minimize it.
