### ISSUE TITLE
am_pm_clock does not appear to work

### ISSUE THREAD

**Issue by tjquillan** [m-wynn/sddm_wynn-theme#13]
I have am_pm_clock set to true in my user theme config and the time remains in 24 hour format.

**Comment by m-wynn** [comment]
Are you running this from a released version or from git master?  I don't think I got around to making a release with the clock feature.

If you're running from git master, can you paste your entire theme.conf.user?

**Comment by tjquillan** [comment]
I will update to the git master. I was using the release

**Comment by m-wynn** [comment]
Made a new release with the latest commits.
