### ISSUE TITLE
Buttons on secondary monitors appear but don't function with primary_screen_only=true

### ISSUE THREAD

**Issue by nuew** [m-wynn/sddm_wynn-theme#15]
When configured with `primary_screen_only = true`, the control buttons (WM, User Switch, Power) appear on secondary monitors, but do not have the expected effect when pressed, and instead only blur the background.

The expected behavior is either that the buttons are not displayed or are entirely effective, having the normal action either on their monitor, or alternatively, the primary monitor.

SDDM version: 0.18.1
Wynn version: 1.4

**Comment by m-wynn** [comment]
Good find, thanks!

**Comment by nuew** [comment]
Some further testing revealed that this also effects the acceptable use policy button on secondary monitors as well, FYI.

**Comment by m-wynn** [comment]
Ah, I'll look into that as well

**Comment by m-wynn** [comment]
Should all be fixed now.  Thanks for the report
