### ISSUE TITLE
Cannot change the background image in configure file and in plasma settings.

### ISSUE THREAD

**Issue by ghost** [m-wynn/sddm_wynn-theme#5]
My desktop environment is Plasma by KDE, more details please see below:

![image](https://user-images.githubusercontent.com/17667917/31161447-b5cfff70-a909-11e7-82f0-f084faa4d27e.png)

The content of the **theme.conf.user**  file likes below:

```
[General]
background=anotherBackground.png
type=image
```

And the content of the **theme.conf** file likes below:

```
[General]
default_background=background.png
default_session=plasma
accent1=#4dd0e1
accent2=#00796b
accent2_hover=#009688
user_name=select
```

the size of my background image is **1920 X 1297**

Is there any mistake I have made? If so, I will appreciate it if you can tell me.

**Comment by m-wynn** [comment]
Hi foreverBirds!

Your theme.conf.user file looks like it was made for a different theme.  I outline the variables you can use in the readme file.  I think you'll want to have a theme.conf.user that looks like:

```ini
[General]
default_background=anotherBackground.png
```

Sorry about that confusion.

**Comment by foreverBirds** [comment]
I have already try to do that. But it doesn't work.

**Comment by ghost** [comment]
thank you for helping me to solve problems
