### ISSUE TITLE
User avatar redraw

### ISSUE THREAD

**Issue by EricKotato** [m-wynn/sddm_wynn-theme#9]
Greetings.

Found a strange bug: just after booting user avatar on LoginFrame not draws until you hover it with mouse or selecting other user. After this bug disappears until next boot (even SDDM restart does not cause it).

So, fix is not clear. There is [this line](https://github.com/m-wynn/sddm_wynn-theme/blob/318a6c4b6b3ebcffe08d9d635fa81425ee19461d/UserAvatar.qml#L10):
```
onSourceChanged: delayPaintTimer.running = true
```
Which starts timer on changing `source` property that after 150ms [executes redraw](https://github.com/m-wynn/sddm_wynn-theme/blob/318a6c4b6b3ebcffe08d9d635fa81425ee19461d/UserAvatar.qml#L42):
```
onTriggered: avatar.requestPaint()
```
Only time when timer does not execute is just after booting.

But if we change `onSourceChanged` to:
```
onSourceChanged: avatar.requestPaint()
```
It will draw just fine.

So I have a question: is that timer in any way important to avatar redraw?

**Comment by m-wynn** [comment]
Hmm.  I took most of the avatar stuff from the [deepin theme](https://github.com/Match-Yang/sddm-deepin/blob/master/deepin/UserAvatar.qml).  I haven't gotten around to rewriting that part.

I don't have this issue on my machine, so maybe it's an issue with a specific version.  I'm going to try to rewrite it without Canvas and see if that helps.

**Comment by m-wynn** [comment]
Can you try my [fix_avatar](https://github.com/m-wynn/sddm_wynn-theme/tree/fix_avatar) branch and see if that works like it should?

**Comment by EricKotato** [comment]
Yes, now it works as it should.

**Comment by m-wynn** [comment]
Cool, I merged it into master.  Thanks for the report!
